// This source file is part of the Orbit project.
//
// Licensed under the Apache License v2.0

// Created by ASTGen: 2024-10-30
// DO NOT EDIT THIS FILE

#ifndef ORBIT_LIFTOFF_PARSER_AST_H_
#define ORBIT_LIFTOFF_PARSER_AST_H_

#include <cassert>
#include <vector>

#include <orbit/orbiter/datatype/orstring.h>
#include <orbit/orbiter/memory/memory.h>

#include <orbit/liftoff/scanner/token.h>
#include <orbit/liftoff/symtable.h>

namespace liftoff::parser {
enum class NodeType {
    ASSIGNMENT,
    ASSIGNMENTS,
    VAR_DECLARATION,
    VAR_DECLARATIONS,
    BINARY,
    CHAN_SEND,
    ELVIS,
    IN,
    NOT_IN,
    NULL_COALESCING,
    SELECTOR,
    SYNC_BLOCK,
    BLOCK,
    BRANCH,
    CALL,
    FUNCTION,
    IDENTIFIER,
    DICT,
    LIST,
    SET,
    TUPLE,
    LITERAL,
    MODULE,
    NAMED_ARG,
    NAMED_PARAM,
    KW_PARAM,
    PARAM,
    REST_PARAM,
    INDEX,
    SLICE,
    AWAIT,
    CHAN_RECV,
    DEFER,
    ELLIPSIS,
    KW_ARG,
    NIL_SAFE,
    PANIC,
    SPAWN,
    TRAP,
    UNARY,
    UPDATE,
};


template<typename T>
    class ASTHandle {
        static_assert(std::is_pointer_v<T>, "T must be a pointer type");
        static_assert(std::is_base_of_v<struct ASTNode, std::remove_pointer_t<T> >,
                      "T must be a pointer to ASTNode or a type derived from ASTNode");

        T node_;

    public:
        ASTHandle() noexcept : node_(nullptr) {
        }

        explicit ASTHandle(T node) noexcept : node_(node) {
        }

        ASTHandle(const ASTHandle &) = delete;

        ASTHandle(ASTHandle &&other) noexcept : node_(other.node_) {
            other.node_ = nullptr;
        }

        template<typename U, typename = std::enable_if_t<std::is_convertible_v<U, T> > >
        ASTHandle(ASTHandle<U> &&other) noexcept : node_(other.release()) {
        }

        ~ASTHandle() noexcept {
            this->reset();
        }

        ASTHandle &operator=(const ASTHandle &) = delete;

        ASTHandle &operator=(ASTHandle &&other) noexcept {
            if (this != &other) {
                this->reset();

                this->node_ = other.node_;

                other.node_ = nullptr;
            }

            return *this;
        }

        template<typename U, typename = std::enable_if_t<std::is_convertible_v<U, T> > >
        ASTHandle &operator=(ASTHandle<U> &&other) noexcept {
            this->reset();

            this->node_ = static_cast<T>(other.release());

            return *this;
        }

        explicit operator bool() const noexcept { return this->node_ != nullptr; }

        std::remove_pointer_t<T> &operator*() const { return *this->node_; }

        T operator->() const noexcept { return this->node_; }

        [[nodiscard]] T get() const noexcept { return this->node_; }

        T release() noexcept {
            T temp = this->node_;
            
            this->node_ = nullptr;

            return temp;
        }

        void reset() noexcept {
            if (this->node_ != nullptr) {
                ASTNodeCleanup(this->node_);
                
                this->node_ = nullptr;
            }
        }
    };

struct ASTNode {
    NodeType node_type;
    scanner::Loc loc;
};

struct Assignment: ASTNode {
    scanner::TokenType token_type;
    ASTNode* name;
    ASTNode* value;
    bool constant;
    bool weak;
};

struct Binary: ASTNode {
    scanner::TokenType token_type;
    ASTNode* left;
    ASTNode* right;
};

struct Block: ASTNode {
    std::vector<ASTHandle<ASTNode*>> statements;
};

struct Branch: ASTNode {
    ASTNode* test;
    ASTNode* body;
    ASTNode* orelse;
};

struct Call: ASTNode {
    ASTNode* left;
    std::vector<ASTHandle<ASTNode*>> args;
    ASTNode* kwargs;
};

struct Function: ASTNode {
    orbiter::datatype::ORString* name;
    orbiter::datatype::ORString* doc;
    std::vector<ASTHandle<ASTNode*>> params;
    ASTNode* body;
    ASTNode* ret_type;
    bool async;
    bool anon;
    bool constant;
    bool pub;
};

struct Identifier: ASTNode {
    orbiter::datatype::ORString* value;
};

struct ListExpression: ASTNode {
    std::vector<ASTHandle<ASTNode*>> elements;
};

struct Literal: ASTNode {
    orbiter::datatype::OObject* literal;
};

struct Module: ASTNode {
    orbiter::datatype::ORString* filename;
    orbiter::datatype::ORString* filepath;
    orbiter::datatype::ORString* docstring;
    std::vector<ASTHandle<ASTNode*>> statements;
    std::vector<orbiter::datatype::HORString> exports;
    std::vector<orbiter::datatype::HORString> imports;
    SymbolTable* sym_t;
};

struct Parameter: ASTNode {
    orbiter::datatype::ORString* id;
    ASTNode* value;
};

struct Subscript: ASTNode {
    ASTNode* expression;
    ASTNode* start;
    ASTNode* stop;
    ASTNode* step;
};

struct Unary: ASTNode {
    scanner::TokenType token_type;
    ASTNode* value;
};

inline void ASTNodeCleanup(ASTNode* ast_node) {
    if (ast_node == nullptr) return;
    
    switch (ast_node->node_type) {
        case NodeType::ASSIGNMENT:         case NodeType::ASSIGNMENTS:         case NodeType::VAR_DECLARATION:         case NodeType::VAR_DECLARATIONS:         {
                auto* node = (Assignment*)ast_node;
        if (node->name)
            ASTNodeCleanup(node->name);
        if (node->value)
            ASTNodeCleanup(node->value);
                break;
            }         case NodeType::BINARY:         case NodeType::CHAN_SEND:         case NodeType::ELVIS:         case NodeType::IN:         case NodeType::NOT_IN:         case NodeType::NULL_COALESCING:         case NodeType::SELECTOR:         case NodeType::SYNC_BLOCK:         {
                auto* node = (Binary*)ast_node;
        if (node->left)
            ASTNodeCleanup(node->left);
        if (node->right)
            ASTNodeCleanup(node->right);
                break;
            }         case NodeType::BLOCK: {
                auto* node = (Block*)ast_node;
        node->statements.~vector();
                break;
            }         case NodeType::BRANCH: {
                auto* node = (Branch*)ast_node;
        if (node->test)
            ASTNodeCleanup(node->test);
        if (node->body)
            ASTNodeCleanup(node->body);
        if (node->orelse)
            ASTNodeCleanup(node->orelse);
                break;
            }         case NodeType::CALL: {
                auto* node = (Call*)ast_node;
        if (node->left)
            ASTNodeCleanup(node->left);
        node->args.~vector();
        if (node->kwargs)
            ASTNodeCleanup(node->kwargs);
                break;
            }         case NodeType::FUNCTION: {
                auto* node = (Function*)ast_node;
        Release(node->name);
        Release(node->doc);
        node->params.~vector();
        if (node->body)
            ASTNodeCleanup(node->body);
        if (node->ret_type)
            ASTNodeCleanup(node->ret_type);
                break;
            }         case NodeType::IDENTIFIER: {
                auto* node = (Identifier*)ast_node;
        Release(node->value);
                break;
            }         case NodeType::DICT:         case NodeType::LIST:         case NodeType::SET:         case NodeType::TUPLE:         {
                auto* node = (ListExpression*)ast_node;
        node->elements.~vector();
                break;
            }         case NodeType::LITERAL: {
                auto* node = (Literal*)ast_node;
        Release(node->literal);
                break;
            }         case NodeType::MODULE: {
                auto* node = (Module*)ast_node;
        Release(node->filename);
        Release(node->filepath);
        Release(node->docstring);
        node->statements.~vector();
        node->exports.~vector();
        node->imports.~vector();
        SymbolTableDel(node->sym_t);
                break;
            }         case NodeType::NAMED_ARG:         case NodeType::NAMED_PARAM:         case NodeType::KW_PARAM:         case NodeType::PARAM:         case NodeType::REST_PARAM:         {
                auto* node = (Parameter*)ast_node;
        Release(node->id);
        if (node->value)
            ASTNodeCleanup(node->value);
                break;
            }         case NodeType::INDEX:         case NodeType::SLICE:         {
                auto* node = (Subscript*)ast_node;
        if (node->expression)
            ASTNodeCleanup(node->expression);
        if (node->start)
            ASTNodeCleanup(node->start);
        if (node->stop)
            ASTNodeCleanup(node->stop);
        if (node->step)
            ASTNodeCleanup(node->step);
                break;
            }         case NodeType::AWAIT:         case NodeType::CHAN_RECV:         case NodeType::DEFER:         case NodeType::ELLIPSIS:         case NodeType::KW_ARG:         case NodeType::NIL_SAFE:         case NodeType::PANIC:         case NodeType::SPAWN:         case NodeType::TRAP:         case NodeType::UNARY:         case NodeType::UPDATE:         {
                auto* node = (Unary*)ast_node;
        if (node->value)
            ASTNodeCleanup(node->value);
                break;
            }
        default:
            assert(false && "Unknown node type");
            break;
    }
    
    orbiter::memory::Free(ast_node);
}


template <typename Derived>
struct ASTVisitor {
    ASTNode* visit(ASTNode* node) {
        switch(node->node_type) {
        case NodeType::ASSIGNMENT:
        case NodeType::ASSIGNMENTS:
        case NodeType::VAR_DECLARATION:
        case NodeType::VAR_DECLARATIONS:
            return static_cast<Derived*>(this)->visitAssignment((Assignment *) node);
        case NodeType::BINARY:
        case NodeType::CHAN_SEND:
        case NodeType::ELVIS:
        case NodeType::IN:
        case NodeType::NOT_IN:
        case NodeType::NULL_COALESCING:
        case NodeType::SELECTOR:
        case NodeType::SYNC_BLOCK:
            return static_cast<Derived*>(this)->visitBinary((Binary *) node);
        case NodeType::BLOCK: return static_cast<Derived*>(this)->visitBlock((Block *) node);
        case NodeType::BRANCH: return static_cast<Derived*>(this)->visitBranch((Branch *) node);
        case NodeType::CALL: return static_cast<Derived*>(this)->visitCall((Call *) node);
        case NodeType::FUNCTION: return static_cast<Derived*>(this)->visitFunction((Function *) node);
        case NodeType::IDENTIFIER: return static_cast<Derived*>(this)->visitIdentifier((Identifier *) node);
        case NodeType::DICT:
        case NodeType::LIST:
        case NodeType::SET:
        case NodeType::TUPLE:
            return static_cast<Derived*>(this)->visitListExpression((ListExpression *) node);
        case NodeType::LITERAL: return static_cast<Derived*>(this)->visitLiteral((Literal *) node);
        case NodeType::MODULE: return static_cast<Derived*>(this)->visitModule((Module *) node);
        case NodeType::NAMED_ARG:
        case NodeType::NAMED_PARAM:
        case NodeType::KW_PARAM:
        case NodeType::PARAM:
        case NodeType::REST_PARAM:
            return static_cast<Derived*>(this)->visitParameter((Parameter *) node);
        case NodeType::INDEX:
        case NodeType::SLICE:
            return static_cast<Derived*>(this)->visitSubscript((Subscript *) node);
        case NodeType::AWAIT:
        case NodeType::CHAN_RECV:
        case NodeType::DEFER:
        case NodeType::ELLIPSIS:
        case NodeType::KW_ARG:
        case NodeType::NIL_SAFE:
        case NodeType::PANIC:
        case NodeType::SPAWN:
        case NodeType::TRAP:
        case NodeType::UNARY:
        case NodeType::UPDATE:
            return static_cast<Derived*>(this)->visitUnary((Unary *) node);
        default: assert(false); return nullptr;
        }
    }
    
    ASTNode* visitAssignment(Assignment* node) { return node; }

    ASTNode* visitBinary(Binary* node) { return node; }

    ASTNode* visitBlock(Block* node) { return node; }

    ASTNode* visitBranch(Branch* node) { return node; }

    ASTNode* visitCall(Call* node) { return node; }

    ASTNode* visitFunction(Function* node) { return node; }

    ASTNode* visitIdentifier(Identifier* node) { return node; }

    ASTNode* visitListExpression(ListExpression* node) { return node; }

    ASTNode* visitLiteral(Literal* node) { return node; }

    ASTNode* visitModule(Module* node) { return node; }

    ASTNode* visitParameter(Parameter* node) { return node; }

    ASTNode* visitSubscript(Subscript* node) { return node; }

    ASTNode* visitUnary(Unary* node) { return node; }
};

inline ASTHandle<Assignment*> MakeAssignment(const scanner::Loc &loc, NodeType node_type) {
    assert(node_type == NodeType::ASSIGNMENT || node_type == NodeType::ASSIGNMENTS || node_type == NodeType::VAR_DECLARATION || node_type == NodeType::VAR_DECLARATIONS);
    auto *node = (Assignment *) orbiter::memory::Calloc(sizeof(Assignment));
    if(node != nullptr) {
        node->node_type = node_type;
        node->loc = loc;
        

    }
    return ASTHandle(node);
}


inline ASTHandle<Binary*> MakeBinary(const scanner::Loc &loc, NodeType node_type) {
    assert(node_type == NodeType::BINARY || node_type == NodeType::CHAN_SEND || node_type == NodeType::ELVIS || node_type == NodeType::IN || node_type == NodeType::NOT_IN || node_type == NodeType::NULL_COALESCING || node_type == NodeType::SELECTOR || node_type == NodeType::SYNC_BLOCK);
    auto *node = (Binary *) orbiter::memory::Calloc(sizeof(Binary));
    if(node != nullptr) {
        node->node_type = node_type;
        node->loc = loc;
        

    }
    return ASTHandle(node);
}


inline ASTHandle<Block*> MakeBlock(const scanner::Loc &loc) {
    auto *node = (Block *) orbiter::memory::Calloc(sizeof(Block));
    if(node != nullptr) {
        node->node_type = NodeType::BLOCK;
        node->loc = loc;
        
        new (&node->statements) std::vector<ASTHandle<ASTNode*>>();
    }
    return ASTHandle(node);
}


inline ASTHandle<Branch*> MakeBranch(const scanner::Loc &loc) {
    auto *node = (Branch *) orbiter::memory::Calloc(sizeof(Branch));
    if(node != nullptr) {
        node->node_type = NodeType::BRANCH;
        node->loc = loc;
        

    }
    return ASTHandle(node);
}


inline ASTHandle<Call*> MakeCall(const scanner::Loc &loc) {
    auto *node = (Call *) orbiter::memory::Calloc(sizeof(Call));
    if(node != nullptr) {
        node->node_type = NodeType::CALL;
        node->loc = loc;
        
        new (&node->args) std::vector<ASTHandle<ASTNode*>>();
    }
    return ASTHandle(node);
}


inline ASTHandle<Function*> MakeFunction(const scanner::Loc &loc) {
    auto *node = (Function *) orbiter::memory::Calloc(sizeof(Function));
    if(node != nullptr) {
        node->node_type = NodeType::FUNCTION;
        node->loc = loc;
        
        new (&node->params) std::vector<ASTHandle<ASTNode*>>();
    }
    return ASTHandle(node);
}


inline ASTHandle<Identifier*> MakeIdentifier(const scanner::Loc &loc) {
    auto *node = (Identifier *) orbiter::memory::Calloc(sizeof(Identifier));
    if(node != nullptr) {
        node->node_type = NodeType::IDENTIFIER;
        node->loc = loc;
        

    }
    return ASTHandle(node);
}


inline ASTHandle<ListExpression*> MakeListExpression(const scanner::Loc &loc, NodeType node_type) {
    assert(node_type == NodeType::DICT || node_type == NodeType::LIST || node_type == NodeType::SET || node_type == NodeType::TUPLE);
    auto *node = (ListExpression *) orbiter::memory::Calloc(sizeof(ListExpression));
    if(node != nullptr) {
        node->node_type = node_type;
        node->loc = loc;
        
        new (&node->elements) std::vector<ASTHandle<ASTNode*>>();
    }
    return ASTHandle(node);
}


inline ASTHandle<Literal*> MakeLiteral(const scanner::Loc &loc) {
    auto *node = (Literal *) orbiter::memory::Calloc(sizeof(Literal));
    if(node != nullptr) {
        node->node_type = NodeType::LITERAL;
        node->loc = loc;
        

    }
    return ASTHandle(node);
}


inline ASTHandle<Module*> MakeModule(const scanner::Loc &loc) {
    auto *node = (Module *) orbiter::memory::Calloc(sizeof(Module));
    if(node != nullptr) {
        node->node_type = NodeType::MODULE;
        node->loc = loc;
        
        new (&node->statements) std::vector<ASTHandle<ASTNode*>>();
        new (&node->exports) std::vector<orbiter::datatype::HORString>();
        new (&node->imports) std::vector<orbiter::datatype::HORString>();
    }
    return ASTHandle(node);
}


inline ASTHandle<Parameter*> MakeParameter(const scanner::Loc &loc, NodeType node_type) {
    assert(node_type == NodeType::NAMED_ARG || node_type == NodeType::NAMED_PARAM || node_type == NodeType::KW_PARAM || node_type == NodeType::PARAM || node_type == NodeType::REST_PARAM);
    auto *node = (Parameter *) orbiter::memory::Calloc(sizeof(Parameter));
    if(node != nullptr) {
        node->node_type = node_type;
        node->loc = loc;
        

    }
    return ASTHandle(node);
}


inline ASTHandle<Subscript*> MakeSubscript(const scanner::Loc &loc, NodeType node_type) {
    assert(node_type == NodeType::INDEX || node_type == NodeType::SLICE);
    auto *node = (Subscript *) orbiter::memory::Calloc(sizeof(Subscript));
    if(node != nullptr) {
        node->node_type = node_type;
        node->loc = loc;
        

    }
    return ASTHandle(node);
}


inline ASTHandle<Unary*> MakeUnary(const scanner::Loc &loc, NodeType node_type) {
    assert(node_type == NodeType::AWAIT || node_type == NodeType::CHAN_RECV || node_type == NodeType::DEFER || node_type == NodeType::ELLIPSIS || node_type == NodeType::KW_ARG || node_type == NodeType::NIL_SAFE || node_type == NodeType::PANIC || node_type == NodeType::SPAWN || node_type == NodeType::TRAP || node_type == NodeType::UNARY || node_type == NodeType::UPDATE);
    auto *node = (Unary *) orbiter::memory::Calloc(sizeof(Unary));
    if(node != nullptr) {
        node->node_type = node_type;
        node->loc = loc;
        

    }
    return ASTHandle(node);
}


} // namespace liftoff::parser
#endif // !ORBIT_LIFTOFF_PARSER_AST_H_