// This source file is part of the Orbit project.
//
// Licensed under the Apache License v2.0

// Created by ASTGen: 2024-10-18
// DO NOT EDIT THIS FILE

#ifndef ORBIT_LIFTOFF_PARSER_AST_H_
#define ORBIT_LIFTOFF_PARSER_AST_H_

#include <cassert>
#include <vector>

#include <orbit/orbiter/datatype/orstring.h>
#include <orbit/orbiter/memory/memory.h>

#include <orbit/liftoff/scanner/token.h>
#include <orbit/liftoff/symtable.h>

namespace liftoff::parser {
    enum class NodeType {
        BINARY,
        IDENTIFIER,
        LITERAL,
        MODULE,
        UNARY,
    };


    template<typename T>
    class ASTHandle {
        static_assert(std::is_pointer_v<T>, "T must be a pointer type");
        static_assert(std::is_base_of_v<struct ASTNode, std::remove_pointer_t<T> >,
                      "T must be a pointer to ASTNode or a type derived from ASTNode");

        T node_;

    public:
        ASTHandle() noexcept : node_(nullptr) {
        }

        explicit ASTHandle(T node) noexcept : node_(node) {
        }

        ASTHandle(const ASTHandle &) = delete;

        ASTHandle(ASTHandle &&other) noexcept : node_(other.node_) {
            other.node_ = nullptr;
        }

        template<typename U, typename = std::enable_if_t<std::is_convertible_v<U, T> > >
        ASTHandle(ASTHandle<U> &&other) noexcept : node_(other.release()) {
        }

        ~ASTHandle() noexcept {
            this->reset();
        }

        ASTHandle &operator=(const ASTHandle &) = delete;

        ASTHandle &operator=(ASTHandle &&other) noexcept {
            if (this != &other) {
                this->reset();

                this->node_ = other.node_;

                other.node_ = nullptr;
            }

            return *this;
        }

        template<typename U, typename = std::enable_if_t<std::is_convertible_v<U, T> > >
        ASTHandle &operator=(ASTHandle<U> &&other) noexcept {
            this->reset();

            this->node_ = static_cast<T>(other.release());

            return *this;
        }

        explicit operator bool() const noexcept { return this->node_ != nullptr; }

        std::remove_pointer_t<T> &operator*() const { return *this->node_; }

        T operator->() const noexcept { return this->node_; }

        [[nodiscard]] T get() const noexcept { return this->node_; }

        T release() noexcept {
            T temp = this->node_;

            this->node_ = nullptr;

            return temp;
        }

        void reset() noexcept {
            if (this->node_ != nullptr) {
                ASTNodeCleanup(this->node_);

                this->node_ = nullptr;
            }
        }
    };

    struct ASTNode {
        NodeType node_type;
        scanner::Loc loc;
    };

    struct Binary : ASTNode {
        scanner::TokenType token_type;
        ASTNode *left;
        ASTNode *right;
    };

    struct Identifier : ASTNode {
        orbiter::datatype::ORString *value;
    };

    struct Literal : ASTNode {
        orbiter::datatype::OObject *literal;
    };

    struct Module : ASTNode {
        orbiter::datatype::ORString *filename;
        orbiter::datatype::ORString *filepath;
        orbiter::datatype::ORString *docstring;
        std::vector<ASTHandle<ASTNode *> > statements;
        SymbolTable *sym_t;
    };

    struct Unary : ASTNode {
        scanner::TokenType token_type;
        ASTNode *value;
    };

    inline void ASTNodeCleanup(ASTNode *ast_node) {
        if (ast_node == nullptr) return;

        switch (ast_node->node_type) {
            case NodeType::BINARY: {
                auto *node = (Binary *) ast_node;
                if (node->left)
                    ASTNodeCleanup(node->left);
                if (node->right)
                    ASTNodeCleanup(node->right);
                break;
            }
            case NodeType::IDENTIFIER: {
                auto *node = (Identifier *) ast_node;
                Release(node->value);
                break;
            }
            case NodeType::LITERAL: {
                auto *node = (Literal *) ast_node;
                Release(node->literal);
                break;
            }
            case NodeType::MODULE: {
                auto *node = (Module *) ast_node;
                Release(node->filename);
                Release(node->filepath);
                Release(node->docstring);
                node->statements.~vector();
                SymbolTableDel(node->sym_t);
                break;
            }
            case NodeType::UNARY: {
                auto *node = (Unary *) ast_node;
                if (node->value)
                    ASTNodeCleanup(node->value);
                break;
            }
            default:
                assert(false && "Unknown node type");
                break;
        }

        orbiter::memory::Free(ast_node);
    }


    template<typename Derived>
    struct ASTVisitor {
        ASTNode *visit(ASTNode *node) {
            switch (node->node_type) {
                case NodeType::BINARY: return static_cast<Derived *>(this)->visitBinary((Binary *) node);
                case NodeType::IDENTIFIER: return static_cast<Derived *>(this)->visitIdentifier((Identifier *) node);
                case NodeType::LITERAL: return static_cast<Derived *>(this)->visitLiteral((Literal *) node);
                case NodeType::MODULE: return static_cast<Derived *>(this)->visitModule((Module *) node);
                case NodeType::UNARY: return static_cast<Derived *>(this)->visitUnary((Unary *) node);
                default: assert(false);
                    return nullptr;
            }
        }

        ASTNode *visitASTNode(ASTNode *node) { return node; }

        ASTNode *visitBinary(Binary *node) { return node; }

        ASTNode *visitIdentifier(Identifier *node) { return node; }

        ASTNode *visitLiteral(Literal *node) { return node; }

        ASTNode *visitModule(Module *node) { return node; }

        ASTNode *visitUnary(Unary *node) { return node; }
    };

    inline ASTHandle<Binary *> MakeBinary(const scanner::Loc &loc) {
        auto *node = (Binary *) orbiter::memory::Calloc(sizeof(Binary));
        if (node != nullptr) {
            node->node_type = NodeType::BINARY;
            node->loc = loc;
        }
        return ASTHandle(node);
    }


    inline ASTHandle<Identifier *> MakeIdentifier(const scanner::Loc &loc) {
        auto *node = (Identifier *) orbiter::memory::Calloc(sizeof(Identifier));
        if (node != nullptr) {
            node->node_type = NodeType::IDENTIFIER;
            node->loc = loc;
        }
        return ASTHandle(node);
    }


    inline ASTHandle<Literal *> MakeLiteral(const scanner::Loc &loc) {
        auto *node = (Literal *) orbiter::memory::Calloc(sizeof(Literal));
        if (node != nullptr) {
            node->node_type = NodeType::LITERAL;
            node->loc = loc;
        }
        return ASTHandle(node);
    }


    inline ASTHandle<Module *> MakeModule(const scanner::Loc &loc) {
        auto *node = (Module *) orbiter::memory::Calloc(sizeof(Module));
        if (node != nullptr) {
            node->node_type = NodeType::MODULE;
            node->loc = loc;

            new(&node->statements) std::vector<ASTHandle<ASTNode *> >();
        }
        return ASTHandle(node);
    }


    inline ASTHandle<Unary *> MakeUnary(const scanner::Loc &loc) {
        auto *node = (Unary *) orbiter::memory::Calloc(sizeof(Unary));
        if (node != nullptr) {
            node->node_type = NodeType::UNARY;
            node->loc = loc;
        }
        return ASTHandle(node);
    }
} // namespace liftoff::parser
#endif // !ORBIT_LIFTOFF_PARSER_AST_H_
